/* Verilog netlist generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 5.2 */
/* C:\lscc\diamond\1.4\ispfpga\bin\nt\scuba.exe -w -n ddr1 -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type iol -mode out -io_type LVCMOS33 -width 1 -freq_in 100 -gear 1 -clk sclk -aligned -e  */
/* Mon Nov 26 15:13:25 2012 */


`timescale 1 ns / 1 ps
module ddr1 (clk, clkout, da, db, q)/* synthesis syn_noprune=1 */;// exemplar attribute ddr1 dont_touch true 
    input wire clk;
    input wire [0:0] da;
    input wire [0:0] db;
    output wire clkout;
    output wire [0:0] q;

    wire buf_clkout;
    wire scuba_vlo;
    wire scuba_vhi;
    wire clkos;
    wire clkop;
    wire buf_qo0;

    OB Inst3_OB (.I(buf_clkout), .O(clkout))
             /* synthesis IO_TYPE="LVCMOS33" */;

    ODDRXD1 Inst_ODDRXD1_0_0 (.DA(da[0]), .DB(db[0]), .SCLK(clkop), .Q(buf_qo0))
             /* synthesis ODDRAPPS="SCLK_ALIGNED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    ODDRXD1 Inst2_ODDRXD1 (.DA(scuba_vhi), .DB(scuba_vlo), .SCLK(clkos), 
        .Q(buf_clkout))
             /* synthesis ODDRAPPS="SCLK_ALIGNED" */;

    OB Inst1_OB0 (.I(buf_qo0), .O(q[0]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    assign clkos = clk;
    assign clkop = clk;


    // exemplar begin
    // exemplar attribute Inst3_OB IO_TYPE LVCMOS33
    // exemplar attribute Inst_ODDRXD1_0_0 ODDRAPPS SCLK_ALIGNED
    // exemplar attribute Inst2_ODDRXD1 ODDRAPPS SCLK_ALIGNED
    // exemplar attribute Inst1_OB0 IO_TYPE LVCMOS33
    // exemplar end

endmodule
