/* Verilog netlist generated by SCUBA Diamond_1.4_Production (87) */
/* Module Version: 5.2 */
/* C:\lscc\diamond\1.4\ispfpga\bin\nt\scuba.exe -w -n sdr_15bit -lang verilog -synth synplify -bus_exp 7 -bb -arch ep5c00 -type iol -mode out -io_type LVCMOS33 -width 15 -freq_in 100 -clk sclk -aligned -gear 0 -e  */
/* Tue Aug 21 17:31:24 2012 */


`timescale 1 ns / 1 ps
module sdr_15bit (clk, clkout, reset, d, dout)/* synthesis syn_noprune=1 */;// exemplar attribute sdr_15bit dont_touch true 
    input wire clk;
    input wire reset;
    input wire [14:0] d;
    output wire clkout;
    output wire [14:0] dout;

    wire buf_clkout;
    wire scuba_vlo;
    wire scuba_vhi;
    wire buf_douto14;
    wire buf_douto13;
    wire buf_douto12;
    wire buf_douto11;
    wire buf_douto10;
    wire buf_douto9;
    wire buf_douto8;
    wire buf_douto7;
    wire buf_douto6;
    wire buf_douto5;
    wire buf_douto4;
    wire buf_douto3;
    wire buf_douto2;
    wire buf_douto1;
    wire buf_douto0;

    OB Inst4_OB (.I(buf_clkout), .O(clkout))
             /* synthesis IO_TYPE="LVCMOS33" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    ODDRXD1 Inst3_ODDRXD1 (.DA(scuba_vhi), .DB(scuba_vlo), .SCLK(clk), .Q(buf_clkout))
             /* synthesis ODDRAPPS="SCLK_ALIGNED" */;

    OFS1P3DX Inst2_OFS1P3DX14 (.D(d[14]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto14));

    OFS1P3DX Inst2_OFS1P3DX13 (.D(d[13]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto13));

    OFS1P3DX Inst2_OFS1P3DX12 (.D(d[12]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto12));

    OFS1P3DX Inst2_OFS1P3DX11 (.D(d[11]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto11));

    OFS1P3DX Inst2_OFS1P3DX10 (.D(d[10]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto10));

    OFS1P3DX Inst2_OFS1P3DX9 (.D(d[9]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto9));

    OFS1P3DX Inst2_OFS1P3DX8 (.D(d[8]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto8));

    OFS1P3DX Inst2_OFS1P3DX7 (.D(d[7]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto7));

    OFS1P3DX Inst2_OFS1P3DX6 (.D(d[6]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto6));

    OFS1P3DX Inst2_OFS1P3DX5 (.D(d[5]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto5));

    OFS1P3DX Inst2_OFS1P3DX4 (.D(d[4]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto4));

    OFS1P3DX Inst2_OFS1P3DX3 (.D(d[3]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto3));

    OFS1P3DX Inst2_OFS1P3DX2 (.D(d[2]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto2));

    OFS1P3DX Inst2_OFS1P3DX1 (.D(d[1]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto1));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    OFS1P3DX Inst2_OFS1P3DX0 (.D(d[0]), .SP(scuba_vhi), .SCLK(clk), .CD(reset), 
        .Q(buf_douto0));

    OB Inst1_OB14 (.I(buf_douto14), .O(dout[14]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB13 (.I(buf_douto13), .O(dout[13]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB12 (.I(buf_douto12), .O(dout[12]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB11 (.I(buf_douto11), .O(dout[11]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB10 (.I(buf_douto10), .O(dout[10]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB9 (.I(buf_douto9), .O(dout[9]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB8 (.I(buf_douto8), .O(dout[8]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB7 (.I(buf_douto7), .O(dout[7]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB6 (.I(buf_douto6), .O(dout[6]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB5 (.I(buf_douto5), .O(dout[5]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB4 (.I(buf_douto4), .O(dout[4]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB3 (.I(buf_douto3), .O(dout[3]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB2 (.I(buf_douto2), .O(dout[2]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB1 (.I(buf_douto1), .O(dout[1]))
             /* synthesis IO_TYPE="LVCMOS33" */;

    OB Inst1_OB0 (.I(buf_douto0), .O(dout[0]))
             /* synthesis IO_TYPE="LVCMOS33" */;



    // exemplar begin
    // exemplar attribute Inst4_OB IO_TYPE LVCMOS33
    // exemplar attribute Inst3_ODDRXD1 ODDRAPPS SCLK_ALIGNED
    // exemplar attribute Inst1_OB14 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB13 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB12 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB11 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB10 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB9 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB8 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB7 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB6 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB5 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB4 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB3 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB2 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB1 IO_TYPE LVCMOS33
    // exemplar attribute Inst1_OB0 IO_TYPE LVCMOS33
    // exemplar end

endmodule
